server:
  port: 8081
spring:
  application:
    name: bl-test-webflux
  profiles:
    group:
      "yue": "bl-webflux,bl-data-mybatis,bl-data-redis"
      "test-confidential": "test-confidential"
      "test-performance": "test-performance"
      "test-confidential-performance": "test-confidential-performance"
    active: yue,test-confidential
