server:
  port: 8081
spring:
  application:
    name: yue-library-test-webflux
  profiles:
    group:
      "yue": "yue-library-webflux,yue-library-data-mybatis,yue-library-data-redis"
      "test-confidential": "test-confidential"
      "test-performance": "test-performance"
      "test-confidential-performance": "test-confidential-performance"
    active: yue,test-confidential
