spring:
  config:
    activate:
      on-profile: yue-library-data-redis

  # 下述Redisson配置会被识别为文本（即：单个value），会被全覆盖，不能增量配置，因此下面调优配置需要复制到对应服务中才好生效
#  redis:
#    redisson:
#      config: |
#        masterSlaveServersConfig:
#          masterAddress: "rediss://master.cache.amazonaws.com:6379"
#          slaveAddresses:
#            - "rediss://replica.cache.amazonaws.com:6379"
#          password: password123
#          connectTimeout: 60000             # 连接超时（需大于命令执行超时），单位毫秒，默认：10000
#          timeout: 20000                    # 命令执行超时，单位毫秒，默认：3000
#          idleConnectionTimeout: 60000      # 空闲连接存活时间，单位毫秒，默认：10000
#          dnsMonitoringInterval: -1         # 关闭dns监控，主从都是单节点，无需检查节点健康，解决aws dns频繁解析限流问题
#          masterConnectionPoolSize: 128     # 写节点连接池最大大小，默认：64
#          slaveConnectionPoolSize: 128      # 读节点连接池最大大小，默认：64
#        protocol: RESP3                     # Redis协议版本，默认：RESP2
#        threads: 32                         # Redis队列监听与执行线程池大小，默认：16
#        nettyThreads: 72                    # Redis命令执行线程池大小，默认：32
#        lazyInitialization: true            # 延迟初始化，默认：false

  # 下述Redisson配置会被识别为文本（即：单个value），会被全覆盖，不能增量配置，因此下面调优配置需要复制到对应服务中才好生效
#  redis:
#    redisson:
#      config: |
#        clusterServersConfig:
#          nodeAddresses:
#            - "rediss://127.0.0.1:7004"
#            - "rediss://127.0.0.1:7001"
#            - "rediss://127.0.0.1:7000"
#          password: password123
#          scanInterval: 10000                     # Redis 集群拓扑扫描间隔，单位毫秒，默认：5000
#          sslEnableEndpointIdentification: false  # 禁用SSL证书域名校验，默认：true
#          connectTimeout: 60000                   # 连接超时（需大于命令执行超时），单位毫秒，默认：10000
#          timeout: 20000                          # 命令执行超时，单位毫秒，默认：3000
#          idleConnectionTimeout: 60000            # 空闲连接存活时间，单位毫秒，默认：10000
#          dnsMonitoringInterval: -1               # 关闭dns监控，主从都是单节点，无需检查节点健康，解决aws dns频繁解析限流问题
#          masterConnectionPoolSize: 128           # 写节点连接池最大大小，默认：64
#          slaveConnectionPoolSize: 128            # 读节点连接池最大大小，默认：64
#        protocol: RESP3                           # Redis协议版本，默认：RESP2
#        threads: 32                               # Redis队列监听与执行线程池大小，默认：16
#        nettyThreads: 72                          # Redis命令执行线程池大小，默认：32
#        lazyInitialization: true                  # 延迟初始化，默认：false

jetcache:
  areaInCacheName: false                          # 是否使用areaName作为cacheName前缀，默认值：false

  local:
    default:
      type: caffeine                              # 使用caffeine本地缓存
      limit: 3000                                 # 每个缓存实例的最大元素数量（控制内存占用），默认：100
      keyConvertor: fastjson2                     # key转换器，默认：fastjson2
      expireAfterAccessInMillis: 86400000         # 缓存未使用的过期时间，解决冷数据、赃数据等问题，单位毫秒（86400000=1天），默认值：不过期

  remote:
    default:
      type: redisson                              # 使用redisson客户端
      keyPrefix: "Cacheable:"                     # 缓存key前缀，默认值：""
      expireAfterWriteInMillis: 604800000         # 缓存过期时间，解决冷数据、赃数据等问题，单位毫秒（604800000=7天），默认值：不过期
      keyConvertor: fastjson2                     # key转换器，默认：fastjson2
      broadcastChannel: default                   # 缓存同步频道（使用default频道并开启缓存同步，当多个服务共用一个频道时，可能会造成广播风暴，这时可以在各自服务中自定义频道)，默认值：无（不开启缓存同步）
