server:
  port: 8080
spring:
  application:
    name: bl-test
  profiles:
    group:
      "yue": "bl-web,bl-data-mybatis,bl-data-redis"
      "test-confidential": "test-confidential"
      "test-performance": "test-performance"
      "test-confidential-performance": "test-confidential-performance"
    active: yue,test-confidential
#    active: yue,test-performance
#    active: yue,test-confidential-performance
